language: php
php:
  - hhvm
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

matrix:
  allow_failures:
    - php: hhvm


before_script:
  - composer install --dev --no-interaction

script: phpunit  --configuration dev/tests/phpunit.xml




