language: php
php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0



before_script:
  - composer install --dev --no-interaction

script: phpunit  --coverage-clover build/logs/clover.xml --configuration dev/tests/phpunit.xml

after_script:
  - php vendor/bin/coveralls -v



